variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dmaven.compiler.showWarnings=false -Dmaven.compiler.debug=false -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS"

image: maven:3-openjdk-11

include:
  - template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - test
  - verify
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  except:
    - tags

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

coverage:
  stage: verify
  script:
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
  coverage: '/(\d+\.?\d*) \% covered/'
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH && $CI_COMMIT_TAG == null

codacy:
  stage: verify
  script:
    - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacoco.xml
  rules:
    - if: $CODACY_PROJECT_TOKEN && $CI_COMMIT_TAG == null

sast:
  stage: test
  variables:
    SAST_EXCLUDED_PATHS: "jacoco-resources, prism.js, src/it/simple-it"

spotbugs-sast:
  variables:
    SAST_JAVA_VERSION: 11

release:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -s ci_settings.xml -am deploy -ntp -Dchangelist= -Psources,javadocs,sign-and-deploy
  only:
    - tags

pages:
  stage: deploy
  script:
    - cp changelog.md src/site/markdown
    - mvn $MAVEN_CLI_OPTS -pl . verify site site:stage -Dchangelist= -Pjavadocs,site
  artifacts:
    paths:
      - public
  only:
    - tags
